name: Publish Module
on:
  push:
    branches:
      - main
jobs:
  install-and-check:
    run: echo The tag is ${{secrets.CODECOV_TOKEN}}
    uses: lifion/core-commons/.github/workflows/publish-module.yml@main
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

  npm-publish:
    run: echo The tag is ${{secrets.NPM_AUTH_TOKEN}}
    uses: lifion/core-commons/.github/workflows/publish-module.yml@main
    secrets:
      NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
