name: Pull-Request Check
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  check:
    uses: lifion/core-commons/.github/workflows/pull-request-check.yml@main
    secrets:
      CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
